"""Remocao tabela NparaN

Revision ID: 031ab05147bd
Revises: 986e3ab066f6
Create Date: 2020-08-29 13:23:53.491370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031ab05147bd'
down_revision = '986e3ab066f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas_professor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turmas_professor',
    sa.Column('prof_id', sa.INTEGER(), nullable=True),
    sa.Column('turma_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['prof_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], )
    )
    # ### end Alembic commands ###
