"""Criacao Professor

Revision ID: 986e3ab066f6
Revises: f29c9744d1d2
Create Date: 2020-08-29 12:59:54.822386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986e3ab066f6'
down_revision = 'f29c9744d1d2'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("professor_id", 'professor', ['professor_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('type')

    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_constraint('professor_id', type_='foreignkey')
        # batch_op.drop_column('professor_id')

    op.drop_table('professor')
    ### end Alembic commands ###

