"""Classes

Revision ID: e371c152e723
Revises: 031ab05147bd
Create Date: 2020-08-29 14:10:35.899518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e371c152e723'
down_revision = '031ab05147bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professor')
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_constraint('professor_id', type_='foreignkey')
        batch_op.create_foreign_key('professor_id', 'usuarios', ['professor_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adm_info', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('aluno_info', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('professor_info', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('professor_info')
        batch_op.drop_column('aluno_info')
        batch_op.drop_column('adm_info')

    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_constraint('professor_id', type_='foreignkey')
        batch_op.create_foreign_key('professor_id', 'professor', ['professor_id'], ['id'])

    op.create_table('professor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
