"""initial

Revision ID: f29c9744d1d2
Revises: 
Create Date: 2020-08-29 08:45:58.068587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29c9744d1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashSenha', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('materia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materia'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas_professor',
    sa.Column('prof_id', sa.Integer(), nullable=True),
    sa.Column('turma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prof_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas_professor')
    op.drop_table('turmas')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
