"""empty message

Revision ID: 0234f77469c2
Revises: 70ceadd77860
Create Date: 2020-09-18 20:34:14.829840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0234f77469c2'
down_revision = '70ceadd77860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_professor',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prof_id'], ['usuarios.id'], name=op.f('fk_turma_professor_prof_id_usuarios')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_turma_professor_turma_id_turmas')),
    sa.PrimaryKeyConstraint('turma_id', 'prof_id', name=op.f('pk_turma_professor'))
    )
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_turmas_professor_id_usuarios', type_='foreignkey')
        batch_op.drop_column('professor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professor_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_turmas_professor_id_usuarios', 'usuarios', ['professor_id'], ['id'])

    op.drop_table('turma_professor')
    # ### end Alembic commands ###
