"""Initial

Revision ID: 0b84f23e8b3b
Revises: 
Create Date: 2020-08-29 14:13:17.746841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b84f23e8b3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashSenha', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('professor_info', sa.String(), nullable=True),
    sa.Column('aluno_info', sa.String(), nullable=True),
    sa.Column('adm_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('materia', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia'], ['materias.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
