"""empty message

Revision ID: 1b4da5044dc8
Revises: f27a8827a757
Create Date: 2020-09-09 13:50:35.295539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b4da5044dc8'
down_revision = 'f27a8827a757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], name=op.f('fk_postagens_professor_id_usuarios')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_postagens_turma_id_turmas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_postagens'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postagens')
    # ### end Alembic commands ###
