"""empty message

Revision ID: 23014a8907c7
Revises: 
Create Date: 2020-08-20 14:55:59.774548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23014a8907c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('materia', sa.Integer(), nullable=False),
    sa.Column('professor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia'], ['materias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
