"""empty message

Revision ID: 49a0c6df4b25
Revises: 70ceadd77860
Create Date: 2020-09-18 19:59:28.308772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a0c6df4b25'
down_revision = '70ceadd77860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_professor',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('prof_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prof_id'], ['usuarios.id'], name=op.f('fk_turma_professor_prof_id_usuarios')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_turma_professor_turma_id_turmas')),
    sa.PrimaryKeyConstraint('turma_id', 'prof_id', name=op.f('pk_turma_professor'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_professor')
    # ### end Alembic commands ###
