"""empty message

Revision ID: 70ceadd77860
Revises: 4bc806afab17
Create Date: 2020-09-14 17:48:10.164964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70ceadd77860'
down_revision = '4bc806afab17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_alunos',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], name=op.f('fk_turma_alunos_aluno_id_usuarios')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_turma_alunos_turma_id_turmas')),
    sa.PrimaryKeyConstraint('turma_id', 'aluno_id', name=op.f('pk_turma_alunos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_alunos')
    # ### end Alembic commands ###
