"""empty message

Revision ID: a5e24bf7dba2
Revises: 9bd6bd064343
Create Date: 2020-09-20 08:14:57.592887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e24bf7dba2'
down_revision = '9bd6bd064343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video', sa.Text(), nullable=True))
        batch_op.drop_column('link')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postagens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.TEXT(), nullable=True))
        batch_op.drop_column('video')

    # ### end Alembic commands ###
