"""empty message

Revision ID: b6e32302bda3
Revises: 5bba7a344b18
Create Date: 2020-08-13 09:03:00.265210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e32302bda3'
down_revision = '5bba7a344b18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('papel', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'papel')
    # ### end Alembic commands ###
