"""empty message

Revision ID: e757ed492afd
Revises: 
Create Date: 2020-09-11 07:51:05.120718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e757ed492afd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materias'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashSenha', sa.String(), nullable=False),
    sa.Column('aluno_info', sa.String(), nullable=True),
    sa.Column('adm_info', sa.String(), nullable=True),
    sa.Column('professor_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('fk_turmas_materia_id_materias')),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], name=op.f('fk_turmas_professor_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turmas'))
    )
    op.create_table('turma_alunos',
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['usuarios.id'], name=op.f('fk_turma_alunos_aluno_id_usuarios')),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_turma_alunos_turma_id_turmas')),
    sa.PrimaryKeyConstraint('turma_id', 'aluno_id', name=op.f('pk_turma_alunos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_alunos')
    op.drop_table('turmas')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
