"""empty message

Revision ID: f1869a672be1
Revises: 70ceadd77860
Create Date: 2020-09-19 09:54:22.397909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1869a672be1'
down_revision = '70ceadd77860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], name=op.f('fk_modulos_turma_id_turmas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modulos'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modulos')
    # ### end Alembic commands ###
