"""Initial migration

Revision ID: f27a8827a757
Revises: 
Create Date: 2020-09-04 23:25:42.573826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27a8827a757'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materias'))
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('hashSenha', sa.String(), nullable=False),
    sa.Column('aluno_info', sa.String(), nullable=True),
    sa.Column('adm_info', sa.String(), nullable=True),
    sa.Column('professor_info', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('materia_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], name=op.f('fk_turmas_materia_id_materias')),
    sa.ForeignKeyConstraint(['professor_id'], ['usuarios.id'], name=op.f('fk_turmas_professor_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turmas'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turmas')
    op.drop_table('usuarios')
    op.drop_table('materias')
    # ### end Alembic commands ###
